name: Hello World CI

on:
  push:
    branches:
      - main   # Run pipeline on pushes to main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Run Hello World
        run: python hello.py
